In [108]:
import groebner, multi_power, multi_cheb
from multi_cheb import MultiCheb
from maxheap import Term
import numpy as np
from scipy.linalg import lu


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [109]:
A = MultiCheb(np.array([[0,1],[2,3]]))
B = MultiCheb(np.array([[2,1],[3,4]]))
C = MultiCheb(np.array([[0,2],[2,4]]))
D = multi_cheb.MultiCheb(np.array([[1,1,1],[2,2,2],[3,3,3]]))

In [110]:
grob = groebner.Groebner([A,B,C,D])
print([i.val for i in grob.matrix_terms])
print(grob.np_matrix)

[(2, 2), (2, 1), (1, 2), (2, 0), (1, 1), (0, 2), (1, 0), (0, 1), (0, 0)]
[[ 3.  3.  2.  3.  2.  1.  2.  1.  1.]
 [ 0.  0.  0.  0.  4.  0.  2.  2.  0.]
 [ 0.  0.  0.  0.  4.  0.  3.  1.  2.]
 [ 0.  0.  0.  0.  3.  0.  2.  1.  0.]]


In [111]:
grob.add_s_to_matrix()


ValueError: operands could not be broadcast together with shapes (3,3) (5,5) 

In [15]:
grob.add_r_to_matrix()
grob.matrix = grob.matrix.loc[:, (grob.matrix != 0).any(axis=0)]
print(grob.matrix)

# Reorder correctly
ord_mat = grob.matrix[['[2 2]', '[2 1]', '[1 2]', '[2 0]', '[1 1]', '[0 2]','[1 0]', '[0 1]', '[0 0]']]
grob_mat = ord_mat.values

new_mat_index = ord_mat.columns.values

new_mat = np.vstack((grob_mat[3:], grob_mat[:3])) # Put R on top for reduction

P,L,U = lu(new_mat)
P_argmax = np.argmax(P,axis=0)

print(U[-6:])

[[ 0.    0.    0.    0.    0.    0.    1.   -1.   -4.  ]
 [ 0.    0.    0.    0.    4.    0.    3.    1.    1.  ]
 [ 0.    0.    0.    0.    0.    0.   -0.25  0.25  0.25]
 [ 0.    0.    0.    0.    0.    0.   -1.    1.    4.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.   -0.75]]


In [25]:
a = np.zeros((3,3))
a[0,1] = 1
print(a)
a = MultiCheb(a)
b = MultiCheb(np.arange(1,10).reshape(3,3))
print(b.coeff)

[[ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
c = a*b
print(c.coeff)

[[  0.5   1.    0.5   1.    0. ]
 [  2.    5.5   2.    2.5   0. ]
 [  3.5  10.    3.5   4.    0. ]
 [  0.    0.    0.    0.    0. ]
 [  0.    0.    0.    0.    0. ]]


In [24]:
d = np.array([[0,1,2,3,0],[0,4,5,6,0],[0,7,8,9,0],[0,0,0,0,0],[0,0,0,0,0]])
e = MultiCheb(2*c.coeff  - d)
print(d)

[[0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [21]:
print(b.coeff)
print(e.coeff)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1.   1.  -1.  -1.   0.]
 [  4.   7.  -1.  -1.   0.]
 [  7.  13.  -1.  -1.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]


In [10]:
a = MultiCheb(np.array([[0,0],[0,1]]))
b = MultiCheb(np.array([[0,0],[3,4]]))

c = a*b
print(c.coeff)
d = np.array([[0,0,0],[0,0,0],[0,3,4]])
e = MultiCheb(2*c.coeff  - d)

print(b.coeff)
print(e.coeff)

[[ 2.   1.5  0. ]
 [ 0.   0.   0. ]
 [ 0.   1.5  2. ]]
[[0 0]
 [3 4]]
[[ 4.  3.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [62]:
a = np.array([[ 0.,  0.,  0.,  0.]])
b = np.array([[ 0.,  0.,  0.,  0.],
 [ 4.,  2.,  2.,  0.],
 [ 4.,  3.,  1.,  2.],
 [ 3.,  2.,  1.,  0.]])

In [69]:
print(a.shape)
print(b.shape)
c = np.hstack((b,a.T))
print(c)

(1, 4)
(4, 4)
[[ 0.  0.  0.  0.  0.]
 [ 4.  2.  2.  0.  0.]
 [ 4.  3.  1.  2.  0.]
 [ 3.  2.  1.  0.  0.]]
