In [11]:
import groebner, multi_power, multi_cheb
from multi_cheb import MultiCheb
from maxheap import Term
import numpy as np
from scipy.linalg import lu


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
A = MultiCheb(np.array([[1,1],[2,3]]))
B = MultiCheb(np.array([[1,1],[3,4]]))
C = MultiCheb(np.array([[5,2],[2,4]]))
#D = multi_cheb.MultiCheb(np.array([[1,1,1],[2,2,2],[3,3,3]]))

In [5]:
grob = groebner.Groebner([A,B,C])
grob.add_s_to_matrix()
print(grob.matrix)
grob.calc_s(A,B).coeff

[[ 4.  2.  2.  5.]
 [ 4.  3.  1.  1.]
 [ 3.  2.  1.  1.]]
   [0 0]  [0 1]  [0 2]  [1 0]  [1 1]  [1 2]  [2 0]  [2 1]  [2 2]
0    1.0    1.0    0.0    2.0    3.0    0.0    0.0    0.0    0.0
0    1.0    1.0    0.0    3.0    4.0    0.0    0.0    0.0    0.0
0    5.0    2.0    0.0    2.0    4.0    0.0    0.0    0.0    0.0
0    0.0    0.0    0.0   -1.0   -1.0    0.0    0.0    0.0    0.0
0   -4.0   -1.0    0.0    0.0   -1.0    0.0    0.0    0.0    0.0
0   -4.0   -1.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0


array([[ 0.,  0.,  0.],
       [-1., -1.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
print([i.val for i in grob.matrix_terms])
print(grob.np_matrix)

[(1, 1), (1, 0), (0, 1), (0, 0)]
[[ 4.  2.  2.  5.]
 [ 4.  3.  1.  1.]
 [ 3.  2.  1.  1.]]


In [15]:
grob.add_r_to_matrix()
grob.matrix = grob.matrix.loc[:, (grob.matrix != 0).any(axis=0)]
print(grob.matrix)

# Reorder correctly
ord_mat = grob.matrix[['[2 2]', '[2 1]', '[1 2]', '[2 0]', '[1 1]', '[0 2]','[1 0]', '[0 1]', '[0 0]']]
grob_mat = ord_mat.values

new_mat_index = ord_mat.columns.values

new_mat = np.vstack((grob_mat[3:], grob_mat[:3])) # Put R on top for reduction

P,L,U = lu(new_mat)
P_argmax = np.argmax(P,axis=0)

print(U[-6:])

[[ 0.    0.    0.    0.    0.    0.    1.   -1.   -4.  ]
 [ 0.    0.    0.    0.    4.    0.    3.    1.    1.  ]
 [ 0.    0.    0.    0.    0.    0.   -0.25  0.25  0.25]
 [ 0.    0.    0.    0.    0.    0.   -1.    1.    4.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.   -0.75]]
