In [1]:
import groebner_class, multi_power, multi_cheb
from multi_cheb import MultiCheb
from multi_power import MultiPower
from maxheap import Term
import numpy as np
from scipy.linalg import lu


%load_ext autoreload
%autoreload 2

In [2]:
A = MultiCheb(np.array([[1,1],[2,3]]))
B = MultiCheb(np.array([[1,1],[3,4]]))
C = MultiCheb(np.array([[5,2],[2,4]]))
#D = multi_cheb.MultiCheb(np.array([[1,1,1],[2,2,2],[3,3,3]]))

In [5]:
grob = groebner.Groebner([A,B,C])
grob.add_s_to_matrix()
print(grob.np_matrix)
grob.calc_s(A,B).coeff

<class 'type'>
<class 'multi_cheb.MultiCheb'>
False
True
True
<class 'type'>
<class 'multi_cheb.MultiCheb'>
False
True
True
<class 'type'>
<class 'multi_cheb.MultiCheb'>
False
True
True
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1. -4.]
 [ 0.  0.  0.  0. -1.  0.  0. -1. -4.]
 [ 0.  0.  0.  0. -1.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  3.  1.  1.]
 [ 0.  0.  0.  0.  3.  0.  2.  1.  1.]]
<class 'type'>
<class 'multi_cheb.MultiCheb'>
False
True
True


array([[ 0.,  0.,  0.],
       [-1., -1.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
print([i.val for i in grob.matrix_terms])
print(grob.np_matrix)

[(2, 2), (2, 1), (1, 2), (2, 0), (1, 1), (0, 2), (1, 0), (0, 1), (0, 0)]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1. -4.]
 [ 0.  0.  0.  0. -1.  0.  0. -1. -4.]
 [ 0.  0.  0.  0. -1.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  3.  1.  1.]
 [ 0.  0.  0.  0.  3.  0.  2.  1.  1.]]


In [8]:
grob.add_r_to_matrix()
grob.np_matrix = grob.np_matrix.loc[:, (grob.matrix != 0).any(axis=0)]
print(grob.matrix)

# Reorder correctly
ord_mat = grob.np_matrix[['[2 2]', '[2 1]', '[1 2]', '[2 0]', '[1 1]', '[0 2]','[1 0]', '[0 1]', '[0 0]']]
grob_mat = ord_mat.values

new_mat_index = ord_mat.columns.values

new_mat = np.vstack((grob_mat[3:], grob_mat[:3])) # Put R on top for reduction

P,L,U = lu(new_mat)
P_argmax = np.argmax(P,axis=0)

print(U[-6:])

IndexError: index 65 is out of bounds for axis 1 with size 65

In [9]:
import numpy as np
T = np.random.rand( 4, 3, 5, 2 )
np.allclose( T.flatten( )[ ::-1 ].reshape( T.shape ) , T[ ::-1, ::-1, ::-1, ::-1 ] )

True

In [2]:
f1 = MultiPower(np.array([[0,-1.5,.5,],[-1.5,1.5,0],[1,0,0,]]))
f2 = MultiPower(np.array([[0,0,0],[-1,0,1],[0,0,0]]))
f3 = MultiPower(np.array([[0,-1,0,1],[0,0,0,0],[0,0,0,0],[0,0,0,0]]))

In [3]:
print(f1.coeff)
print(f2.coeff)
print(f3.coeff)

[[ 0.  -1.5  0.5]
 [-1.5  1.5  0. ]
 [ 1.   0.   0. ]]
[[ 0  0  0]
 [-1  0  1]
 [ 0  0  0]]
[[ 0 -1  0  1]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]


In [4]:
poly_list = [f1, f2, f3]

In [37]:
from vector_space import VectorSpace
vs = VectorSpace()

In [38]:
print(vs.makeBasis(poly_list))

In [39]:
from itertools import product

In [47]:
l = [tuple(j) for j in f1.degrevlex_gen()]
for i in l: print(i)

(2.0, 2.0)
(2.0, 1.0)
(1.0, 2.0)
(2.0, 0.0)
(1.0, 1.0)
(0.0, 2.0)
(1.0, 0.0)
(0.0, 1.0)
(0.0, 0.0)
