In [1]:
import groebner, multi_power, multi_cheb
from maxheap import Term
import numpy as np

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
A = multi_cheb.MultiCheb(np.array([[1,1],[2,3]]))
B = multi_cheb.MultiCheb(np.array([[1,1],[3,4]]))
C = multi_cheb.MultiCheb(np.array([[5,2],[2,4]]))
D = multi_cheb.MultiCheb(np.array([[1,1,1],[2,2,2],[3,3,3]]))

In [4]:
grob = groebner.Grobner([A,B,C,D])



Current np_matrix vals: 
[]
Adding poly:
 [[1 1]
 [2 3]]
1
[[ 0.]]
1
[[ 0.]]
1
[[ 0.]]
1
[[ 0.]]
Current np_matrix vals: 
[[ 0.  0.  0.  0.]
 [ 3.  2.  1.  1.]]
Adding poly:
 [[1 1]
 [3 4]]
Current np_matrix vals: 
[[ 0.  0.  0.  0.]
 [ 4.  3.  1.  1.]
 [ 3.  2.  1.  1.]]
Adding poly:
 [[5 2]
 [2 4]]
Current np_matrix vals: 
[[ 0.  0.  0.  0.]
 [ 4.  2.  2.  5.]
 [ 4.  3.  1.  1.]
 [ 3.  2.  1.  1.]]
Adding poly:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
4
[[ 0.  0.  0.  0.]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [6]:
C.coeff

array([[5, 2],
       [2, 4]])

In [5]:
print(grob.np_matrix)
for i in grob.matrix_terms:
    print(i.val)

NameError: name 'grob' is not defined

In [74]:
print(grob.term_set)

set([(0, 1), (1, 0), (0, 0), (1, 1)])
